name: URL Shortener

title: URL Shortener
description: Create short URLs that can be easily shared!

version: v0.2

baseurl: ""
permalink: /:slug/
logo: /assets/newLogo.png
favicon: /assets/logo.png

theme: jekyll-theme-minimal

plugins:
  - jekyll-redirect-from

collections:
  urls:
    output: true
    permalink: /:slug

whitelist:
  - jekyll-redirect-from

redirect_from:
  json: false

include:
  - _urls

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - /_urls/repo.md
